{
 "title": "Overview",
 "time": { "from": "2023-01-04T02:06:11.108Z", "to": "2023-01-04T02:06:34.881Z" },
 "panels": [
  {
   "title": "All Data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"log-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] != \"Time\" and r[\"_field\"] != \"AFR WB-B1\" and r[\"_field\"] != \"AFR WB-B2\" and r[\"_field\"] != \"ENG OIL TEMP\" and r[\"_field\"] != \"KNOCK STRENGTH\" and r[\"_field\"] != \"BATTERY VOLT (Volts)\")\n"
    }
   ]
  },
  {
   "title": "Knock strength",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"log-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"KNOCK STRENGTH\")\n"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"log-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"ENG OIL TEMP\")\n"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"log-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY VOLT (Volts)\")\n"
    }
   ]
  },
  {
   "title": "A/F Ratios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"log-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"AFR WB-B1\" or r[\"_field\"] == \"AFR WB-B2\")\n"
    }
   ]
  }
 ]
}